async function runDocPipelineTest() {
  console.log('[TEST] Step 1: Creating session...');
  const sessRes = await fetch('http://localhost:3000/api/sessions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ scenarioId: 1, personaIds: [1, 2] })
  });
  const sessData = await sessRes.json();
  const sessionId = sessData.session.id;
  console.log(`[TEST] Created session: ${sessionId}`);

  // Create a sample technical pitch deck text simulating a parsed PDF/PPTX
  const samplePdfText = `
    PROJECT: AgriEasy AI Smart Irrigation Platform
    ARCHITECTURE: Microservices deployed on AWS EKS with Node.js and PostgreSQL.
    IOT HARDWARE: ESP32 soil moisture sensors communicating via MQTT broker (Mosquitto).
    KEY METRICS: Serves 50,000 active farms across North America with 99.95% uptime.
    COST: Monthly AWS cloud infrastructure spending is $8,500.
    CHALLENGES: Sensor network packet loss during heavy rainstorms causing data latency spikes up to 45 seconds.
  `;
  const fileBase64 = Buffer.from(samplePdfText).toString('base64');

  console.log('[TEST] Step 2: Uploading PDF/PPTX project document...');
  const docRes = await fetch(`http://localhost:3000/api/sessions/${sessionId}/documents`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      fileName: 'AgriEasy_System_Architecture_Deck.txt',
      fileBase64
    })
  });
  const docData = await docRes.json();
  console.log(`[TEST] Document upload response:`, docData);

  // Wait 2 seconds for background question generation
  await new Promise(r => setTimeout(r, 2500));

  console.log('[TEST] Step 3: Fetching session questions generated by LLM from uploaded document...');
  const sRes = await fetch(`http://localhost:3000/api/sessions/${sessionId}`);
  const sData = await sRes.json();

  console.log(`\n=== GENERATED DOCUMENT-SPECIFIC QUESTIONS (${sData.questions?.length || 0}) ===`);
  (sData.questions || []).forEach((q, idx) => {
    console.log(`[${idx + 1}] Persona ${q.personaId} (${q.source}): "${q.question}"`);
  });

  if (sData.questions && sData.questions.length > 0) {
    console.log('\n✅ DOCUMENT PIPELINE & LLM DYNAMIC QUESTION GENERATION PASSED!');
  } else {
    console.log('\n❌ DOCUMENT PIPELINE FAILED: No questions generated.');
  }
}

runDocPipelineTest().catch(console.error);
